version: '3'



services:
  profile-service:
    build: ./profile-service
    ports:
      - '5000:5000'
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_HOST=postgres
    networks:
      - microservices_network

  auth-service:
    build: ./auth-service
    ports:
      - '5001:5001'
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_HOST=postgres
    networks:
      - microservices_network

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always
    networks:
      - microservices_network

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '2fde7fd2'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'project-base'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always
    networks:
      - microservices_network

networks:
  microservices_network:

volumes:
  postgres-data: